### ISSUE TITLE
First initial meeting

### ISSUE THREAD

**Issue by pherterich** [CERNStudyGroup/cernstudygroup.github.io#1]
**Date**: 19 Feb 2016
**Time**: 17:00 CET (UTC +01)
**Location**: CERN Restaurant 1 (the "IKEA" section), moving to a meeting room if needed
**Session format**: [INTRO](https://cernstudygroup.github.io/presentations/01-intro) + Hacky Hour

---

Just come if you're interested and want to have some fun. Let us know what you'd like to share or learn by filling this short survey beforehand (especially if you can't make it in person on the 19th): https://docs.google.com/forms/d/1z07RWOD1NKGfcDCAJrMju5rpsmat76jaeHcLv9m3rqI/viewform

---

[![Join the chat at https://gitter.im/CERNStudyGroup/cernstudygroup.github.io](https://badges.gitter.im/CERNStudyGroup/cernstudygroup.github.io.svg)](https://gitter.im/CERNStudyGroup/cernstudygroup.github.io)
Introduce yourself (#26) and list your project(s) (#24).

---

**Participated**:
- @jacquerie
- @pherterich 
- @daslerr
- @stevelaskaridis
- @ozel
- @RaoOfPhysics

**Comment by betatim** [comment]
Do you want to start so soon? I think it would be good to have a topic and speaker lined up for the first meeting (maybe "How to use github to take part in planning this meetup"?) Maybe survey people via an email to all the lists as to what they'd like to hear about. If we collect a lot of people in a room with little structure it might just be silence-of-the-masses or someone monopolising the mic. Or maybe have a "hacky hour" event to kick things off?

Friday 5pm is "prime time" no? Do we want to start in a time slot that has a lot of competition? Thoughts on holding it after lunch or in the morning (basically during working hours).

**Comment by ibab** [comment]
Yeah, I'm also for careful preparation in advance.
But if the others would like to have a more informal planning meeting with only a few people, I'm not against it.
It would be nice to have a plan in case a lot of people shop up, like a presentation on how to use git and
Github.

**Comment by RaoOfPhysics** [comment]
@betatim: The reason we didn't start earlier was because I procrastinated endlessly on this. I think it's good for us to set a start date, even if it seems too close to today.

In any case, as I understand it, the Study Groups are not meant to follow the "speaker+audience" format, but are supposed to be a place for people to come together and work on their respective projects, getting help from others as needed, like a "Hacky Hour".

I would therefore suggest we meet, give an overview of what we're going to do at the Study Groups, and introduce some projects so people know what to expect.

I am, of course, completely open to the idea of surveying people before the first session so WE know what THEY expect as well.

I'm also fine with us moving it to an earlier slot during the day: 15:00? But let's maybe keep this first session at the 17:00 slot and test the waters?

Also, I think an introduction to Git, GitHub and also CERN's hosted instance of GitLab would be welcome, maybe for Session 2. Volunteers? ;)

**Comment by betatim** [comment]
I was thinking the first session would be [work-along](https://mozillascience.github.io/studyGroupHandbook/event-types.html#workalong) style. (Tells you about my biases :smile_cat:)

Personally no time slot on that day works as I will be away from CERN, it was more a general comment that Friday afternoon is usually when people are thinking about the weekend or have already left. So I was thinking it would make it harder for us to persuade people to come ;) When an event takes place also sets the tone/expectation. At least I go to an event scheduled at 7pm with very different expectations than one at 10am. Usually the former means: drinks, chit-chat, arrive +-30min, talk about whatever with others, relax whereas the latter means: concentrate, arrive on time, engage my brain, want to learn something. This is probably very subjective. So I think depending on what atmosphere we want, we should consider this (not sure if either of them is better or worse).

Having a "vision" at the first event to let people know what it is about is a good idea. Then listen to what people actually want and tweak. I was thinking of the pre-event survey as a way to help come up with a vision that isn't a million miles away from what people want.

**Comment by RaoOfPhysics** [comment]
You're spot on, @betatim. We (you, @ibab, @pherterich and I?) should have a chat later this week or early next week (Vidyo participation welcome, @ibab!) to iron details out.

**Comment by ibab** [comment]
Yes, I can join over Vidyo!

**Comment by seneubert** [comment]
If there is Vidyo (and/or slack) I would join as well. Just for an hour, because Friday evening there are serious social obligations to fulfil ;)

**Comment by betatim** [comment]
I'd discourage vidyo/remote for the actual meeting. Though I think here we
have moved on to discussing the meeting zero to plan meeting one for which
remote is fine.

**Comment by RaoOfPhysics** [comment]
@betatim is right -- I meant Vidyo for the planning meeting. Given that the actually Study Group sessions will be in R1 (at least the first) it would be good if people could be there in person.

However, perhaps we could use Gitter for remote participants? :D

**Comment by RaoOfPhysics** [comment]
[![Join the chat at https://gitter.im/CERNStudyGroup/cernstudygroup.github.io](https://badges.gitter.im/CERNStudyGroup/cernstudygroup.github.io.svg)](https://gitter.im/CERNStudyGroup/cernstudygroup.github.io)

**Comment by RaoOfPhysics** [comment]
Are we doing a planning meeting this week? I'm away tomorrow and on Thursday morning. Can join on Thursday afternoon.

**Comment by betatim** [comment]
I'm out all week, but you don't really need me.

**Comment by RaoOfPhysics** [comment]
We neeeeeeeed you, Tiiiiiiim!

**Comment by lukasheinrich** [comment]
since, I'm still based in NY, I'll probably only join for the first meeting that is remote, otherwise I should be showing up at CERN around summer.

**Comment by RaoOfPhysics** [comment]
@lukasheinrich: :+1:  Don't think we'll have remote participation for the first one, but if we do in the future, I'll add Vidyo links to the issues. :)

**Comment by ibab** [comment]
I'm based in Manchester right now, so I won't be able to attend in person. Would be nice if we can set up Vidyo at some point, but it has to fit with the format of the study group (We wouldn't want this to become yet another of those CERN Vidyo meetings).

**Comment by RaoOfPhysics** [comment]
> We wouldn't want this to become yet another of those CERN Vidyo meetings.

![](https://i.imgur.com/BlFKF0r.jpg)

**Comment by lukasheinrich** [comment]
agreed to all of the above points. not sure what the best way is to have something more immersive/interactive than vidyo that also works remotely. surely, other people have faced this problem, maybe there are some solutions?

**Comment by betatim** [comment]
I think the only solution is: no remotes :(

**Comment by lukasheinrich** [comment]
yeah, I was suspecting that :-/ I vote for more travel money.

**Comment by RaoOfPhysics** [comment]
So, who's coming today?

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Find <a href="https://twitter.com/PHerterich">@pherterich</a> or me at today&#39;s <a href="https://twitter.com/CERN">@CERN</a> <a href="https://twitter.com/hashtag/mozstudy?src=hash">#mozstudy</a> session to get your Research Fox sticker! <a href="https://t.co/c97nE9w9gL">https://t.co/c97nE9w9gL</a> <a href="https://t.co/Mfb3rshM9g">https://t.co/Mfb3rshM9g</a></p>&mdash; Achintya Rao (@RaoOfPhysics) <a href="https://twitter.com/RaoOfPhysics/status/700617575059722242">February 19, 2016</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by tpmccauley** [comment]
I cannot alas. Enjoy.

**Comment by JoeriHermans** [comment]
I'm still in Belgium :( I will attend next time!

**Comment by Cotera** [comment]
Where are everybody? I'm looking for you... If someone reads me in 5 minutes I'd like to join, otherwise, next time...

**Comment by betatim** [comment]
Hi, I think the plan was to meet in R1.

**Comment by Cotera** [comment]
There I'm, I don't see any group..

**Comment by betatim** [comment]
That is a shame. I'm unfortunately not at cern either. Lesson for next time
bigger sign/better definition of meeting point.

**Comment by pherterich** [comment]
Sorry, I guess my Mozilla Science Lab shirt was not visible enough once we sat down and started talking (and it got more crowded here).  We'll print a huuuge sign for next week.

**Comment by RaoOfPhysics** [comment]
@Cotera: Apologies! We waited for about 15 minutes and then sat down. We were (I think!) the only folk with laptops in the glass extension, so I hoped we could be found easily. We'll have clearer marking next time if we meet in a crowded space.
