### ISSUE TITLE
Github org logo

### ISSUE THREAD

**Issue by betatim** [CERNStudyGroup/cernstudygroup.github.io#10]
Calling all artists: the github organisation needs a logo!

Any ideas?

**Comment by betatim** [comment]
Maybe we can entice @kdungs or @eamonnmag?

**Comment by eamonnmag** [comment]
![msl](https://cloud.githubusercontent.com/assets/282396/13123799/506e2afa-d5be-11e5-9ac2-ec0ed9b2a5b8.png)

**Comment by eamonnmag** [comment]
![msl2](https://cloud.githubusercontent.com/assets/282396/13124135/fa833fe8-d5bf-11e5-979f-ee2172682066.png)

**Comment by eamonnmag** [comment]
Tried to make it look a little like the MSL logo, but with a brain instead to show collective knowledge. Each dot represents a person for instance, with colour representing their domain. The second one has particles coming in to it to bring a subtle hint of particle physics, and also show that the closer you get, the bigger they get, which is bringing the idea that by coming together, your knowledge can increase. That's a lot of cheese, but it makes sense :p

**Comment by betatim** [comment]
CERN font for the writing and CERN written in CERN blue?

Paging @auremoser to get her to point us to where it says yay/nay on using the MSL logo

**Comment by eamonnmag** [comment]
![msl3](https://cloud.githubusercontent.com/assets/282396/13124617/91cf471a-d5c1-11e5-8be0-7fed20052adf.png)

**Comment by lukasheinrich** [comment]
like it!

**Comment by ibab** [comment]
Very cool! :tada:

**Comment by suenjedt** [comment]
Nice!

**Comment by kdungs** [comment]
Awesome, Eamon! :tophat: 

Btw., does the use of the font and colour require permission by CERN?

**Comment by betatim** [comment]
Aren't you glad the lawyers have arrived? :P

**Comment by eamonnmag** [comment]
I don't think so. Although I've never actually directly used their font
since I think it's a bit rubbish. I have rarely had trouble with them
though. Using the colour for sure is fine. The font,  maybe not, but
eyeballing it,  it's not a special font.

**Comment by kdungs** [comment]
Okay, I was only worried because I know that they are very protective when it comes to (ab)use of their logo.

**Comment by eamonnmag** [comment]
They definitely have brand guidelines. I'd need to check if using the CERN
text directly is against those. It can be easier to just use a different
(better),  but close font.

**Comment by auremoser** [comment]
Very late to the game, thanks for adding me @betatim, we're fine being included, or alluded to, in the design :). I can't speak for CERN though.

**Comment by adavidzh** [comment]
_cough_ comic _cough_ sans _cough_
(Damned cough)

**Comment by auremoser** [comment]
nothing says "legit science project" like a cameo from comic sans.

**Comment by eamonnmag** [comment]
And a portrait of fabiola :)

**Comment by betatim** [comment]
It is all about [comic neue](http://comicneue.com)

**Comment by betatim** [comment]
@eamonnmag can you make a square version as well for the github org box? Maybe just the colourful points and no writing?

**Comment by eamonnmag** [comment]
![msl_sq](https://cloud.githubusercontent.com/assets/282396/13138230/2a336270-d626-11e5-925a-6a3d53600f0a.png)

**Comment by eamonnmag** [comment]
There you go @betatim

**Comment by RaoOfPhysics** [comment]
I like the idea, but I have to I'm not a fan of the brain design. We're not the Human Brain Project or a neuroscience lab. :P

**Comment by auremoser** [comment]
OMG @betatim I hadn't hear of Commic Neue! <3
@RaoOfPhysics I'm not sure the brainshape is super-strong anyway, it could also be a [bubble chart](http://bl.ocks.org/mbostock/4063269). Logos can be goofy anyway, I mean look at [uber](http://www.elischiff.com/blog/2016/2/16/ubers-atomic-meltdown), trying to get all science-y with the "bits and atoms" stuff.

**Comment by RaoOfPhysics** [comment]
@auremoser: I hadn't even seen the explanation @eamonnmag posted above when I first saw the image and I immediately thought, "That's a brain!" :D

I agree that logos can be goofy, so if the other folk like this and want to go with it, there are no objections from me. :)

**Comment by RaoOfPhysics** [comment]
- https://github.com/CERNStudyGroup
- https://twitter.com/mozstudyCERN
