### ISSUE TITLE
Gitter Sidecar not working well

### ISSUE THREAD

**Issue by RaoOfPhysics** [CERNStudyGroup/cernstudygroup.github.io#13]
So, it looks like the Sidecar is actually overlapping with the webpage's elements. Also the "close" button doesn't work.

Can someone debug locally? @ibab, @betatim? Will need Jekyll installed, and then `jekyll serve`. Sorry for not testing more thoroughly.

**Comment by betatim** [comment]
Can't we remove it? I've never found these build in chat thingies useful.

**Comment by RaoOfPhysics** [comment]
It's kinda useful for those wanting to participate remotely or just ping from time to time, no?

No strong feelings, I just thought it might have practical use.

**Comment by ibab** [comment]
We should revert it now, because it makes the site difficult to use.
Once we can get the close button to not be blocked by the header, we can enable it again.

**Comment by RaoOfPhysics** [comment]
@ibab: Sure. Revert away! I'm not sure how to do all that. :P

**Comment by betatim** [comment]
I an see the close button, but clicking it doesn't do anything :(

**Comment by ibab** [comment]
`git revert bla -m 1` to the rescue in 4fe3687

**Comment by RaoOfPhysics** [comment]
Presumably, we can close this, right?
