### ISSUE TITLE
Introduction to Jupyter notebooks

### ISSUE THREAD

**Issue by RaoOfPhysics** [CERNStudyGroup/cernstudygroup.github.io#21]
**Date**: 4 March 2016
**Time**: 17:00 CET (UTC +01)
**Location**: [4/3-006 (TH Auditorium)](https://maps.cern.ch/mapsearch/mapsearch.htm?n=[%274/3-006%27])
**Vidyo for remote participants** (just click on the link to proceed): [CERN_OpenScience](http://vidyoportal.cern.ch/flex.html?roomdirect.html&key=Y71x6cfIijd0ZKrxesei6NpQ9Q)
**Session format**: [Work-Along](https://mozillascience.github.io/studyGroupHandbook/event-types.html#workalong)
**RSVP**: https://dudle.inf.tu-dresden.de/mozstudyCERN_3/

---

Lesson guide: @betatim
Lesson materials: https://github.com/betatim/studygroupjupyter

---

[![Join the chat at https://gitter.im/CERNStudyGroup/cernstudygroup.github.io](https://badges.gitter.im/CERNStudyGroup/cernstudygroup.github.io.svg)](https://gitter.im/CERNStudyGroup/cernstudygroup.github.io)
If you haven't done so yet, introduce yourself (#26) and list your project(s) (#24).

---

**Participated in person**:
- @RaoOfPhysics 
- @betatim 
- @tpmccauley 
- @daslerr
- @jacquerie
- @AnxhelaDani 
- @pherterich
- @TaiSakuma

**Participated over Vidyo**:
- @ibab 
- @seneubert
- @andrewjohnlowe
- @apuignav
- @pseyfert
- **Lucia Grillo** (GH?)

**Comment by betatim** [comment]
I'd like to volunteer for this lesson.

**Comment by RaoOfPhysics** [comment]
@betatim: Yay! I was going to nominate you in any case. ;)

**Comment by RaoOfPhysics** [comment]
And when you have fancy materials, you can add it here: https://github.com/mozillascience/studyGroupLessons (Maybe host it on our organisation, if you want.)

**Comment by RaoOfPhysics** [comment]
@betatim: Next Friday (4 March)?

**Comment by betatim** [comment]
I'll do it. Be prepared!

![science](http://i.imgur.com/hopuzvW.gif)

**Comment by RaoOfPhysics** [comment]
@betatim: WHOOP!

**Comment by RaoOfPhysics** [comment]
@ibab: @betatim has given permission for remote participants! I've added a Vidyo room to the OP. :D

**Comment by betatim** [comment]
I am developing the material here: https://github.com/betatim/studygroupjupyter

This will be a super interactive session, so bring your laptops and follow the [setup instructions](https://github.com/betatim/studygroupjupyter#setup-construction) before you arrive. This way we
can get going straight away instead of spending a lot of time getting everything working.

If you get stuck post in this thread or create an [issue in `betatim/studygroupjupyter`](https://github.com/betatim/studygroupjupyter/issues).

**Comment by RaoOfPhysics** [comment]
> If you get stuck post in this thread or create an issue in betatim/studygroupjupyter.

Or harass @betatim on Gitter, which is what I did. But I'm happy to note that setup is successfully done. Ready to go.

**Comment by RaoOfPhysics** [comment]
Interesting Notebooks by Peter Norvig: http://norvig.com/ipython/README.html
