### ISSUE TITLE
Show and Tell

### ISSUE THREAD

**Issue by RaoOfPhysics** [CERNStudyGroup/cernstudygroup.github.io#31]
**Date**: 26 Feb 2016
**Time**: 17:00 CET (UTC +01)
**Location**: CERN Restaurant 1 (the "IKEA" section), moving to a meeting room if needed (We'll sign-post it a bit more clearly this time!)
**Session format**: Show and Tell!
**RSVP**: https://dudle.inf.tu-dresden.de/mozstudyCERN_2/

---

Demo your projects and get feedback/collaborators/partners!

---

[![Join the chat at https://gitter.im/CERNStudyGroup/cernstudygroup.github.io](https://badges.gitter.im/CERNStudyGroup/cernstudygroup.github.io.svg)](https://gitter.im/CERNStudyGroup/cernstudygroup.github.io)
If you haven't done so yet, introduce yourself (#26) and list your project(s) (#24).

---

**Participated**:
- @pherterich 
- @jacquerie
- @TaiSakuma
- @SirHalie
- @daslerr
- @RaoOfPhysics
- @suenjedt 
- @xchen101
- @JavierDelgadoFernandez
- @hachreak
- @Cotera

---

**Projects presented / discussed**:
- [SketchUpCMS](https://github.com/SketchUpCMS/SketchUpCMS) - @TaiSakuma
- [senato.py](https://github.com/jacquerie/senato.py) - @jacquerie
- [CERN Analysis Preservation](https://github.com/cernanalysispreservation/analysis-preservation.cern.ch/) - @suenjedt 
- [Open Cosmics](https://github.com/OpenCosmics/opencosmics.github.io) - @RaoOfPhysics
- [PROOF Analysis Framework (PAF)](https://github.com/PROOF-Analysis-Framework/PROOF-Analysis-Framework) - @JavierDelgadoFernandez

---

**Links collection**:
- Modelling:
  - [SketchUp](http://www.sketchup.com/)
- Data Visualisation:
  - [D3](https://d3js.org/)
  - [Raw](http://raw.densitydesign.org/)
- LHC Status:
  - [meltronx](http://www.meltronx.com/)
  - [@LHCstatus](https://twitter.com/lhcstatus)

**Comment by RaoOfPhysics** [comment]
Reminder!

**Comment by pherterich** [comment]
Update: we're in the glassbox in the very far left corner when you enter. I'm in the Mozilla Science Lab T-shirt again, so come and find us!
