### ISSUE TITLE
Meeting 4: Hacky Hour

### ISSUE THREAD

**Issue by RaoOfPhysics** [CERNStudyGroup/cernstudygroup.github.io#34]
**Date**: 11 March 2016
**Time**: 17:00 CET (UTC +01)
**Location**: CERN R1, in the glass extension commonly known as the "IKEA Section". We should be on the far end, near the glass wall facing the Alps.
**No remote participants**
**Session format**: [Hacky Hour](https://mozillascience.github.io/studyGroupHandbook/event-types.html#hackyhour) &mdash; bring your projects with you and let's work over beer

---

[![Join the chat at https://gitter.im/CERNStudyGroup/cernstudygroup.github.io](https://badges.gitter.im/CERNStudyGroup/cernstudygroup.github.io.svg)](https://gitter.im/CERNStudyGroup/cernstudygroup.github.io)
If you haven't done so yet, introduce yourself (#26) and list your project(s) (#24).

---

**Participated**:
- @Tontonis 
- @pherterich 
- @daslerr
- @ozel
- @RaoOfPhysics
- **Massimo Lamanna**

---

**Links collection**:
- Documentation / Text:
  - [ShareLaTeX](https://www.sharelatex.com/) &mdash; and the CERN instance: https://coauthoring.cern.ch/ (now broken!)
  - [MkDocs](http://www.mkdocs.org/)
  - [GitBook](https://www.gitbook.com/) &mdash; [How to set up GitBook at CERN](https://configdocs.web.cern.ch/configdocs/gbook/index.html)
- Cosmic Rays:
  - [Cosmic Pi](http://cosmicpi.org/)
  - [CRAYFIS](http://crayfis.io/)
  - [HiSPARC](http://www.hisparc.nl/en)
- Annotation:
  - [hypothes.is](https://hypothes.is/)

**Comment by RaoOfPhysics** [comment]
I'm going to be working on [Open Cosmics](https://github.com/OpenCosmics), so if there are any cosmic-ray enthusiasts out there, please come along (pinging @Tontonis).

@tpmccauley: ~~If you could point me to the specification for `.ig` files, please. Thanks!~~ [Found it!](https://cms-outreach.github.io/ispy/)

**Comment by Tontonis** [comment]
I'll be there with some stuff to do for Open Cosmics. Finally in the right country to make a session!
