### ISSUE TITLE
Interactive graphics in the browser with WebGL (three.js)

### ISSUE THREAD

**Issue by tpmccauley** [CERNStudyGroup/cernstudygroup.github.io#36]
**Date**: 22 April 2016
**Time**: 17:00 CEST (UTC +02)
**Location**: [40/R-C10](https://maps.cern.ch/mapsearch/mapsearch.htm?n=[%2740/R-C10%27])
**Vidyo for remote participants** (just click on the link to proceed): [CERN_OpenScience](http://vidyoportal.cern.ch/flex.html?roomdirect.html&key=Y71x6cfIijd0ZKrxesei6NpQ9Q)
**Session format**: [Work-Along](https://mozillascience.github.io/studyGroupHandbook/event-types.html#workalong)

---

Lesson guide: @tpmccauley
Lesson materials: https://github.com/tpmccauley/studyGroupWebGL
Slides: http://cmsdoc.cern.ch/~mccauley/studyGroupWebGL/slides/

Please visit http://www.doesmybrowsersupportwebgl.com/ before you come to the session to ensure that your browser supports WebGL.

---

[![Join the chat at https://gitter.im/CERNStudyGroup/cernstudygroup.github.io](https://badges.gitter.im/CERNStudyGroup/cernstudygroup.github.io.svg)](https://gitter.im/CERNStudyGroup/cernstudygroup.github.io)
If you haven't done so yet, introduce yourself (#26) and list your project(s) (#24).

---

**Participated**:
- @AnxhelaDani
- @daslerr
- @piotroramus
- @mickypaganini
- @suenjedt 
- @RaoOfPhysics
- **Saranya Ghosh**
- @Tontonis 
- @TaiSakuma

**Comment by RaoOfPhysics** [comment]
:+1:

**Comment by lukasheinrich** [comment]
shameless plug on a small project I did with three.js + d3.js
https://github.com/lukasheinrich/dynkinweb
http://physics.nyu.edu/~lh1132/dynkinweb/index.html

**Comment by RaoOfPhysics** [comment]
@lukasheinrich: Looks cool but I wish I understood it. :D Would you be interested in demoing it after @tpmccauley's lesson (same day)?

**Comment by lukasheinrich** [comment]
yeah but I'm remote (until summer), so not sure how it would work.

**Comment by RaoOfPhysics** [comment]
Shouldn't be a problem –– we want to offer remote participants the opportunity of joining lessons. :D

**Comment by RaoOfPhysics** [comment]
@lukasheinrich: We're meeting this Friday. ~~Let me know if you want to do a demo of your work over Vidyo. :)~~ On second thought, given how little time we have, maybe we can do a demo another day, perhaps when you're at CERN?

**Comment by lukasheinrich** [comment]
what time are you meeting?

**Comment by tpmccauley** [comment]
If you are attending and are using your own machine I would recommend seeing if WebGL is supported: http://www.doesmybrowsersupportwebgl.com/

**Comment by RaoOfPhysics** [comment]
I would just suggest everyone use Firefox, since @tpmccauley's code is tested on the browser. :)

**Comment by Tontonis** [comment]
Excellent! Will be there!
