### ISSUE TITLE
Principles of Data Visualization

### ISSUE THREAD

**Issue by eamonnmag** [CERNStudyGroup/cernstudygroup.github.io#42]
**Date**: 15 April 2016
**Time**: 17:00 CEST (UTC +02)
**Location**: [40/R-D10](https://maps.cern.ch/mapsearch/mapsearch.htm?n=[%2740/R-D10%27])
**Vidyo for remote participants** (just click on the link to proceed): [CERN_OpenScience](http://vidyoportal.cern.ch/flex.html?roomdirect.html&key=Y71x6cfIijd0ZKrxesei6NpQ9Q)
**Session format**: Talk

---

Lesson guide: @eamonnmag
Lesson materials: https://www.dropbox.com/s/3x4103xbgg1b312/CERN-MozStudy-Principles.pdf?dl=0 

---

[![Join the chat at https://gitter.im/CERNStudyGroup/cernstudygroup.github.io](https://badges.gitter.im/CERNStudyGroup/cernstudygroup.github.io.svg)](https://gitter.im/CERNStudyGroup/cernstudygroup.github.io)
If you haven't done so yet, introduce yourself (#26) and list your project(s) (#24).

---

**Participated in person**:
- @TaiSakuma
- @daslerr
- @Kjili
- @piotroramus
- @ric-bianchi
- @betatim
- **Stefania Pandolfi**
- **Iva Raynova**
- @AnxhelaDani

**Participated via Vidyo**:
- @andrewjohnlowe
- @GraemeWatt
- @rochaporto
- @tpmccauley 
- @xchen101
- @adavidzh

**Comment by lukasheinrich** [comment]
great slides.... sad I can't be there. maybe we can have some remote discussion here: @eamonnmag after having worked bit on the HEP domain, do you have some general comments on how visualization is done in HEP right now? I think the vast majority of visualizations are histograms, mostly since we are interested in relative frequencies of events that can be labeled on continuous scales/axes. are there alternatives to look at? what do you feel is the biggest deficiency in how viz is done in HEP?

L

**Comment by adavidzh** [comment]
@lukasheinrich to me it's the rainbow palette from hell, err, ROOT.

**Comment by adavidzh** [comment]
Thanks for the updates addressing color perception. #KillTheRainbow

**Comment by eamonnmag** [comment]
Some papers on perception being attached:
- [Cleveland and McGill, 1984](https://www.cs.ubc.ca/~tmm/courses/cpsc533c-04-spr/readings/cleveland.pdf)
- [MacKinlay, 1986](http://www2.parc.com/istl/groups/uir/publications/items/UIR-1986-02-Mackinlay-TOG-Automating.pdf)
- [Heer and Bostock, 2010](http://vis.stanford.edu/files/2010-MTurk-CHI.pdf)
- [S.S. Stevens, 1975](https://books.google.ch/books?id=r5JOHlXX8bgC&pg=PA15&redir_esc=y#v=onepage&q&f=false)
- [Chapter 2 of my Thesis](http://ora.ox.ac.uk/objects/uuid:b98ccce1-038f-4c0a-a259-7f53dfe06ac7) - has lots on perception and also the neuroscience explaining various effects

**Comment by adavidzh** [comment]
Any news on the updated slides (as shown)?

**Comment by RaoOfPhysics** [comment]
Pinging @eamonnmag. :)

**Comment by eamonnmag** [comment]
Just updated the link :)
