### ISSUE TITLE
Intro to Docker

### ISSUE THREAD

**Issue by RaoOfPhysics** [CERNStudyGroup/cernstudygroup.github.io#48]
**Date**: 27 May 2016
**Time**: 17:00 CEST (UTC +02)
**Location**: [40/R-D10](https://maps.cern.ch/mapsearch/mapsearch.htm?n=[%2740/R-D10%27])
**Vidyo for remote participants** (just click on the link to proceed): [CERN_OpenScience](http://vidyoportal.cern.ch/flex.html?roomdirect.html&key=Y71x6cfIijd0ZKrxesei6NpQ9Q)
**Session format**: [Work-Along](https://mozillascience.github.io/studyGroupHandbook/event-types.html#workalong)

---

Lesson guide: @tiborsimko
Lesson materials: https://github.com/CERNStudyGroup/cernstudygroup.github.io/issues/48#issuecomment-224649345 More info: http://tiborsimko.org/tag/docker.html

---

[![Join the chat at https://gitter.im/CERNStudyGroup/cernstudygroup.github.io](https://badges.gitter.im/CERNStudyGroup/cernstudygroup.github.io.svg)](https://gitter.im/CERNStudyGroup/cernstudygroup.github.io)
If you haven't done so yet, introduce yourself (#26) and list your project(s) (#24).

---

**Participated in person**:
- @RaoOfPhysics 
- @jacquerie
- @xchen101
- @Kjili
- ??
- ??

**Participated over Vidyo**:
- @tpmccauley
- @andrewjohnlowe
- @pseyfert

**Comment by RaoOfPhysics** [comment]
Confirming date and time!

**Comment by mickypaganini** [comment]
Where can I find the material that was used during this tutorial?

**Comment by tiborsimko** [comment]
@mickypaganini The tutorial was an interactive code-along session style, so there is no formal material.  Although part of the tutorial can be followed by reading [my old blog posts on docker](http://tiborsimko.org/tag/docker.html); see references below. 

Here is a rough "table of contents" of what we touched:
- Introduction
  - Virtual Machines vs Container technology differences
  - Docker image registry (`docker search python`)
  - Pulling an image (`docker pull python:2.7`)
  - Using image locally (`docker run -i -t --rm python:2.7 /bin/bash`)
  - Working with images (`docker image`, `docker rmi`)
  - Images vs Containers
  - Working with containers (`docker ps`, `docker exec`, `docker rm`)
- Simple web application
  - Example: "Hello World" Python web application http://tiborsimko.org/docker-for-python-applications.html
  - Automatising creation of docker images (`Dockerfile`)
  - Optimising docker images: `RUN` commands and image layers
- Composed web application
  - `docker-compose`: starting several containers and inter-linking them (web, db, cache, mq...)
  - Example: limiting web page hits https://github.com/inveniosoftware/flask-ratelimiter/
  - Building app (`docker-compose build`)
  - Running app (`docker-compose up -d`, `docker-compose ps`)
  - Accessing logs (`docker-compose logs`)
- Starting containers on remote machines
  - old low-level approach http://tiborsimko.org/docker-on-cern-openstack.html
  - new `docker-machine` approach; create VM on OpenStack
  - we have seen Docker stack (`docker`, `docker-compose`, `docker-machine`); there are alternative orchestration techniques, Kubernetes, OpenStack Magnum
