### ISSUE TITLE
Writing papers with markdown, GitHub, Authorea and Zenodo

### ISSUE THREAD

**Issue by RaoOfPhysics** [CERNStudyGroup/cernstudygroup.github.io#57]
**Date**: 14 October 2016
**Time**: [17:00 CEST (UTC+02)](http://everytimezone.com/#2016-10-14,180,cn3)
**Location**: [40/R-C10](https://maps.cern.ch/mapsearch/mapsearch.htm?n=[%2740/R-C10%27])
**Vidyo for remote participants** (just click on the link to proceed): [CERN_OpenScience](http://vidyoportal.cern.ch/flex.html?roomdirect.html&key=Y71x6cfIijd0ZKrxesei6NpQ9Q)
**Session format**: [Work-Along](https://mozillascience.github.io/studyGroupHandbook/event-types.html#workalong)

---

Lesson guide: @RaoOfPhysics
Lesson materials: https://github.com/RaoOfPhysics/modern-research-publishing
Topics addressed:
- Getting started with the tools
- Why markdown? / Why not LaTeX?
- Git and branches
- Benefits of using GitHub (over, at the moment, GitLab)
- Authorea and its export options
- Minting DOIs with Zenodo

---
## Resources:
- [What is markdown?](http://kirkstrobeck.github.io/whatismarkdown.com/)
- [Authorea&harr;GitHub](https://www.authorea.com/users/3/articles/17235/_show_article)
- [GitHub&rarr;Zenodo](https://guides.github.com/activities/citable-code/)
- [CERN Bulletin article on the lab's partnership with Authorea](http://cds.cern.ch/journal/CERNBulletin/2015/49/News%20Articles/2105082) a.k.a. free private documents with CERN credentials
- @RaoOfPhysics's example &mdash; conference proceedings:
  - On GitHub: https://github.com/RaoOfPhysics/201607_PCST-Proceedings
    - All mistakes/changes/whatnot: https://github.com/RaoOfPhysics/201607_PCST-Proceedings/commits/master
  - On Zenodo: http://dx.doi.org/10.5281/zenodo.60214
  - On Authorea: https://www.authorea.com/users/8205/articles/116704/_show_article
  - Submitted version: http://www.pcst.co/papers/view/292

---

Before the session, please:
- Install a text editor for working with your markdown files (I use [Atom](https://atom.io/) but Vim works pretty well too)
- Install git on your computer
- Create a GitHub account if you haven't done so
- Create an Authorea account with your CERN e-mail address
- Log in to Zenodo using your GitHub account

---

[![Join the chat at https://gitter.im/CERNStudyGroup/cernstudygroup.github.io](https://badges.gitter.im/CERNStudyGroup/cernstudygroup.github.io.svg)](https://gitter.im/CERNStudyGroup/cernstudygroup.github.io)
If you haven't done so yet, introduce yourself (#26) and list your project(s) (#24).

---
## OP

If anyone is interested in my document-publishing workflow, I'd be happy to do a session sometime in late October.

**Comment by pherterich** [comment]
If I don't get my Vidyo working, could you maybe record it so I can catch up later from a proper computer that actually let's me install useful stuff?

**Comment by RaoOfPhysics** [comment]
@pherterich: Not sure how to record with Vidyo, but I can look into it. Although, you have 24+ hours! Sort out your Vidyo. ;)

**Comment by pherterich** [comment]
I don't have admin rights to my work computer. I'm not able to do s**\* :unamused:

**Comment by RaoOfPhysics** [comment]
Boo. Are you allowed to carry a laptop to work? I'll look into recording options.

**Comment by pherterich** [comment]
Not necessary, after a fight with IT because they're not able, I got it fixed :smile: !!!!

**Comment by pherterich** [comment]
Vidyo plug in doesn't work in any of my 3 browsers :unamused: Sorry, would have loved to join you guys.
