### ISSUE TITLE
Broken links in template

### ISSUE THREAD

**Issue by betatim** [CERNStudyGroup/cernstudygroup.github.io#7]
Not sure what causes this but links in the "Howto be notified" section are broken `http://cernstudygroup.github.io/%7B%7B%20site.github.repository_url%20%7D%7D`. Seems like the template isn't being replaced by the actual URL?

**Comment by adavidzh** [comment]
The template driving this is https://github.com/CERNStudyGroup/cernstudygroup.github.io/blob/master/_data/en.yml#L26

I poked around and the only thing I found was that this seems to be an automatic variable: https://github.com/jekyll/jekyll-help/issues/5#issuecomment-39033862.

The `{{ site.github.repository_url }}` seems to not be properly interpreted. Could this be a bug upstream?

**Comment by betatim** [comment]
Seems so fundamental that I also guess it is upstream, but then https://github.com/UofTCoders/studyGroup seems to work fine :-/

**Comment by adavidzh** [comment]
`UofTCoders` does not have a `_data/en.yml`. Do you know where is their link coming from?
(Github search is really bad: searching for `repository` in our repo yields zero results.)

**Comment by betatim** [comment]
Upstream discussion in mozillascience/studyGroup#47

**Comment by RaoOfPhysics** [comment]
Should we update our website locally?

**Comment by betatim** [comment]
We should ping @ibab to bump mozillascience/studyGroup#48 so that it gets merged upstream.

**Comment by RaoOfPhysics** [comment]
I pinged Abby on that PR.

**Comment by RaoOfPhysics** [comment]
Looks like https://github.com/mozillascience/studyGroup/pull/48 is resolved. Can someone with better Jekyll skillz pull the changes in to our repo?

**Comment by RaoOfPhysics** [comment]
Closed by #23.
